public class Main {
    public static void main(String[] args) throws Exception {
        System.out.println("--- Section 1 ---");
        GhostPokemon g1 = new GhostPokemon();
        FightingPokemon f1 = new FightingPokemon();
        NormalPokemon n1 = new NormalPokemon();
        Pokemon p1 = new Pokemon();
        System.out.println(g1.getName());
        System.out.println(f1.getName());
        System.out.println(n1.getName());
        System.out.println(p1.getName());
        
        GhostPokemon g2 = new GhostPokemon("Gastly");
        FightingPokemon f2 = new FightingPokemon("Machop");
        NormalPokemon n2 = new NormalPokemon("Rattata");
        Pokemon p2 = new Pokemon("Big Boss");
        System.out.println(g2.getName());
        System.out.println(f2.getName());
        System.out.println(n2.getName());
        System.out.println(p2.getName());
        g2.displayClass();
        f2.displayClass();
        n2.displayClass();
        p2.displayClass();
        g1.setUniqueID("G1");
        System.out.println(g1.getUniqueID());
        f1.setUniqueID(12);
        System.out.println(f1.getUniqueID());

        System.out.println("--- Section 2 ---");
        g2.checkElement();
        f2.checkElement();
        n2.checkElement();
        g2.specialSkill();
        f2.displayAura();
        g2.displayAura();
        f2.specialSkill();

        System.out.println("--- Section 3 ---");
        PokemonAction pg2 = new PokemonAction<Pokemon>(g2);
        PokemonAction pn2 = new PokemonAction<Pokemon>(n2);
        pg2.displayPokemonClass();
        pn2.displayPokemonClass();
        System.out.println(g2.getName()+" vs "+n2.getName());
        pg2.attack();
        pn2.defense();
        pg2.attack();
        pn2.defense();
        pg2.attack();
        pn2.defense();
        pg2.attack();
        pn2.defense();
        pg2.attack();
        pn2.defense();
        pg2.attack();
        pn2.defense();
        pg2.attack();
        pn2.defense();
        pn2.attack();
        pg2.defense();
        pn2.attack();
        pg2.defense();
        pn2.attack();
        pg2.defense();
        pn2.useSkill();
        pg2.useSkill();
        pn2.run();

        System.out.println("--- Section 4 ---");
        System.out.println("New Battle Found");
        PokemonAction pp2 = new PokemonAction<Pokemon>(p2);
        PokemonAction pf2 = new PokemonAction<Pokemon>(f2);
        pf2.displayPokemonClass();
        pp2.displayPokemonClass();
        System.out.println(p2.getName()+" vs "+f2.getName());
        pf2.attack();
        pp2.defense();
        pf2.attack();
        pp2.defense();
        pf2.attack();
        pp2.defense();
        pf2.attack();
        pp2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pp2.attack();
        pf2.defense();
        pf2.useSkill();
        pp2.useSkill();
        pf2.run();
        System.out.println("All Battle Finished");
    }
}
